DROP TABLE IF EXISTS __schema__.raw___table__ CASCADE;
CREATE TABLE __schema__.raw___table__
(
    id          integer generated by default as identity primary key,
    ingested_at timestamp default CURRENT_TIMESTAMP,
    data        jsonb not null
);
